#! /bin/sh

sxhkd &

bspc monitor -d Internet Code Terminal Other Music

#bspc config border_width         2
#bspc config window_gap          12
bspc config border_width 5
bspc config window_gap 7

bspc config normal_border_color \#032C36
bspc config focused_border_color \#EEEEEE
bspc config presel_feedback_color \#EEEEEE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a termite floating=on
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Subl3 desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-scale ~/Pictures/Wallpapers/igla.jpg
wal -i ~/Pictures/Wallpapers/igla.jpg
light -S 42
setxkbmap pl
polybar example
